# Form implementation generated from reading ui file 'gui/ui/environment_tab.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EnvironmentTab(object):
    def setupUi(self, EnvironmentTab):
        EnvironmentTab.setObjectName("EnvironmentTab")
        EnvironmentTab.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(EnvironmentTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.path_group = QtWidgets.QGroupBox(parent=EnvironmentTab)
        self.path_group.setObjectName("path_group")
        self.path_layout = QtWidgets.QFormLayout(self.path_group)
        self.path_layout.setObjectName("path_layout")
        self.label = QtWidgets.QLabel(parent=self.path_group)
        self.label.setObjectName("label")
        self.path_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.data_path_layout = QtWidgets.QHBoxLayout()
        self.data_path_layout.setObjectName("data_path_layout")
        self.edit_data_path = QtWidgets.QLineEdit(parent=self.path_group)
        self.edit_data_path.setObjectName("edit_data_path")
        self.data_path_layout.addWidget(self.edit_data_path)
        self.browse_data_btn = QtWidgets.QPushButton(parent=self.path_group)
        self.browse_data_btn.setObjectName("browse_data_btn")
        self.data_path_layout.addWidget(self.browse_data_btn)
        self.path_layout.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.data_path_layout)
        self.verticalLayout.addWidget(self.path_group)
        self.log_group = QtWidgets.QGroupBox(parent=EnvironmentTab)
        self.log_group.setObjectName("log_group")
        self.log_layout = QtWidgets.QFormLayout(self.log_group)
        self.log_layout.setObjectName("log_layout")
        self.label_2 = QtWidgets.QLabel(parent=self.log_group)
        self.label_2.setObjectName("label_2")
        self.log_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.combo_log_level = QtWidgets.QComboBox(parent=self.log_group)
        self.combo_log_level.setObjectName("combo_log_level")
        self.combo_log_level.addItem("")
        self.combo_log_level.addItem("")
        self.log_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.combo_log_level)
        self.label_3 = QtWidgets.QLabel(parent=self.log_group)
        self.label_3.setObjectName("label_3")
        self.log_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.log_path_layout = QtWidgets.QHBoxLayout()
        self.log_path_layout.setObjectName("log_path_layout")
        self.edit_log_path = QtWidgets.QLineEdit(parent=self.log_group)
        self.edit_log_path.setObjectName("edit_log_path")
        self.log_path_layout.addWidget(self.edit_log_path)
        self.browse_log_btn = QtWidgets.QPushButton(parent=self.log_group)
        self.browse_log_btn.setObjectName("browse_log_btn")
        self.log_path_layout.addWidget(self.browse_log_btn)
        self.log_layout.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.log_path_layout)
        self.verticalLayout.addWidget(self.log_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(EnvironmentTab)
        QtCore.QMetaObject.connectSlotsByName(EnvironmentTab)

    def retranslateUi(self, EnvironmentTab):
        _translate = QtCore.QCoreApplication.translate
        EnvironmentTab.setWindowTitle(_translate("EnvironmentTab", "Form"))
        self.path_group.setTitle(_translate("EnvironmentTab", "資料根目錄"))
        self.label.setText(_translate("EnvironmentTab", "數據儲存路徑:"))
        self.browse_data_btn.setText(_translate("EnvironmentTab", "📁 瀏覽"))
        self.log_group.setTitle(_translate("EnvironmentTab", "日誌設定"))
        self.label_2.setText(_translate("EnvironmentTab", "日誌等級:"))
        self.combo_log_level.setItemText(0, _translate("EnvironmentTab", "INFO"))
        self.combo_log_level.setItemText(1, _translate("EnvironmentTab", "DEBUG"))
        self.label_3.setText(_translate("EnvironmentTab", "日誌儲存路徑:"))
        self.browse_log_btn.setText(_translate("EnvironmentTab", "📁 瀏覽"))
