# Form implementation generated from reading ui file 'gui/ui/measurement_tab.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MeasurementTab(object):
    def setupUi(self, MeasurementTab):
        MeasurementTab.setObjectName("MeasurementTab")
        MeasurementTab.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(MeasurementTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.accuracy_group = QtWidgets.QGroupBox(parent=MeasurementTab)
        self.accuracy_group.setObjectName("accuracy_group")
        self.accuracy_layout = QtWidgets.QFormLayout(self.accuracy_group)
        self.accuracy_layout.setObjectName("accuracy_layout")
        self.label = QtWidgets.QLabel(parent=self.accuracy_group)
        self.label.setObjectName("label")
        self.accuracy_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.spin_relay_delay = QtWidgets.QSpinBox(parent=self.accuracy_group)
        self.spin_relay_delay.setMaximum(5000)
        self.spin_relay_delay.setObjectName("spin_relay_delay")
        self.accuracy_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_relay_delay)
        self.label_2 = QtWidgets.QLabel(parent=self.accuracy_group)
        self.label_2.setObjectName("label_2")
        self.accuracy_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.spin_smu_settle = QtWidgets.QSpinBox(parent=self.accuracy_group)
        self.spin_smu_settle.setMaximum(5000)
        self.spin_smu_settle.setObjectName("spin_smu_settle")
        self.accuracy_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_smu_settle)
        self.verticalLayout.addWidget(self.accuracy_group)
        self.safety_group = QtWidgets.QGroupBox(parent=MeasurementTab)
        self.safety_group.setObjectName("safety_group")
        self.safety_layout = QtWidgets.QFormLayout(self.safety_group)
        self.safety_layout.setObjectName("safety_layout")
        self.label_3 = QtWidgets.QLabel(parent=self.safety_group)
        self.label_3.setObjectName("label_3")
        self.safety_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.spin_v_max = QtWidgets.QDoubleSpinBox(parent=self.safety_group)
        self.spin_v_max.setMaximum(210.0)
        self.spin_v_max.setMinimum(0.1)
        self.spin_v_max.setObjectName("spin_v_max")
        self.safety_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_v_max)
        self.label_4 = QtWidgets.QLabel(parent=self.safety_group)
        self.label_4.setObjectName("label_4")
        self.safety_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.spin_i_max = QtWidgets.QDoubleSpinBox(parent=self.safety_group)
        self.spin_i_max.setSingleStep(0.01)
        self.spin_i_max.setMinimum(0.001)
        self.spin_i_max.setMaximum(1.0)
        self.spin_i_max.setObjectName("spin_i_max")
        self.safety_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.spin_i_max)
        self.verticalLayout.addWidget(self.safety_group)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(MeasurementTab)
        QtCore.QMetaObject.connectSlotsByName(MeasurementTab)

    def retranslateUi(self, MeasurementTab):
        _translate = QtCore.QCoreApplication.translate
        MeasurementTab.setWindowTitle(_translate("MeasurementTab", "Form"))
        self.accuracy_group.setTitle(_translate("MeasurementTab", "量測精細度"))
        self.label.setText(_translate("MeasurementTab", "Relay 沉降時間:"))
        self.spin_relay_delay.setSuffix(_translate("MeasurementTab", " ms"))
        self.label_2.setText(_translate("MeasurementTab", "SMU 穩定時間:"))
        self.spin_smu_settle.setSuffix(_translate("MeasurementTab", " ms"))
        self.safety_group.setTitle(_translate("MeasurementTab", "全域安全閘 (Safety Guard)"))
        self.label_3.setText(_translate("MeasurementTab", "系統最高電壓:"))
        self.spin_v_max.setSuffix(_translate("MeasurementTab", " V"))
        self.label_4.setText(_translate("MeasurementTab", "系統最高電流:"))
        self.spin_i_max.setSuffix(_translate("MeasurementTab", " A"))
