# Form implementation generated from reading ui file 'gui/ui/personnel_tab.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PersonnelTab(object):
    def setupUi(self, PersonnelTab):
        PersonnelTab.setObjectName("PersonnelTab")
        PersonnelTab.resize(536, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PersonnelTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_panel = QtWidgets.QGroupBox(parent=PersonnelTab)
        self.user_panel.setObjectName("user_panel")
        self.user_v_layout = QtWidgets.QVBoxLayout(self.user_panel)
        self.user_v_layout.setObjectName("user_v_layout")
        self.user_list = QtWidgets.QListWidget(parent=self.user_panel)
        self.user_list.setObjectName("user_list")
        self.user_v_layout.addWidget(self.user_list)
        self.user_btn_layout = QtWidgets.QHBoxLayout()
        self.user_btn_layout.setObjectName("user_btn_layout")
        self.add_user_btn = QtWidgets.QPushButton(parent=self.user_panel)
        self.add_user_btn.setObjectName("add_user_btn")
        self.user_btn_layout.addWidget(self.add_user_btn)
        self.remove_user_btn = QtWidgets.QPushButton(parent=self.user_panel)
        self.remove_user_btn.setObjectName("remove_user_btn")
        self.user_btn_layout.addWidget(self.remove_user_btn)
        self.user_v_layout.addLayout(self.user_btn_layout)
        self.horizontalLayout.addWidget(self.user_panel)
        self.project_panel = QtWidgets.QGroupBox(parent=PersonnelTab)
        self.project_panel.setObjectName("project_panel")
        self.project_v_layout = QtWidgets.QVBoxLayout(self.project_panel)
        self.project_v_layout.setObjectName("project_v_layout")
        self.project_list = QtWidgets.QListWidget(parent=self.project_panel)
        self.project_list.setObjectName("project_list")
        self.project_v_layout.addWidget(self.project_list)
        self.project_btn_layout = QtWidgets.QHBoxLayout()
        self.project_btn_layout.setObjectName("project_btn_layout")
        self.add_project_btn = QtWidgets.QPushButton(parent=self.project_panel)
        self.add_project_btn.setObjectName("add_project_btn")
        self.project_btn_layout.addWidget(self.add_project_btn)
        self.remove_project_btn = QtWidgets.QPushButton(parent=self.project_panel)
        self.remove_project_btn.setObjectName("remove_project_btn")
        self.project_btn_layout.addWidget(self.remove_project_btn)
        self.project_v_layout.addLayout(self.project_btn_layout)
        self.horizontalLayout.addWidget(self.project_panel)

        self.retranslateUi(PersonnelTab)
        QtCore.QMetaObject.connectSlotsByName(PersonnelTab)

    def retranslateUi(self, PersonnelTab):
        _translate = QtCore.QCoreApplication.translate
        PersonnelTab.setWindowTitle(_translate("PersonnelTab", "Form"))
        self.user_panel.setTitle(_translate("PersonnelTab", "使用者 (Users)"))
        self.add_user_btn.setText(_translate("PersonnelTab", "新增使用者"))
        self.remove_user_btn.setText(_translate("PersonnelTab", "刪除使用者"))
        self.project_panel.setTitle(_translate("PersonnelTab", "專案 (Projects)"))
        self.add_project_btn.setText(_translate("PersonnelTab", "新增專案"))
        self.remove_project_btn.setText(_translate("PersonnelTab", "刪除專案"))
