# Form implementation generated from reading ui file 'gui/ui/system_config.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SystemConfigDialog(object):
    def setupUi(self, SystemConfigDialog):
        SystemConfigDialog.setObjectName("SystemConfigDialog")
        SystemConfigDialog.resize(850, 700)
        self.main_layout = QtWidgets.QVBoxLayout(SystemConfigDialog)
        self.main_layout.setObjectName("main_layout")
        self.tabs = QtWidgets.QTabWidget(parent=SystemConfigDialog)
        self.tabs.setObjectName("tabs")
        self.main_layout.addWidget(self.tabs)
        self.button_box = QtWidgets.QDialogButtonBox(parent=SystemConfigDialog)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.button_box.setObjectName("button_box")
        self.main_layout.addWidget(self.button_box)

        self.retranslateUi(SystemConfigDialog)
        self.tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SystemConfigDialog)

    def retranslateUi(self, SystemConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        SystemConfigDialog.setWindowTitle(_translate("SystemConfigDialog", "系統全域設定"))
